"""add leaderboards table

Revision ID: 8d202f1202b0
Revises: 93e6858602db
Create Date: 2026-05-22 22:00:47.896663

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d202f1202b0"
down_revision: str | Sequence[str] | None = "93e6858602db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leaderboards",
        sa.Column("leaderboard_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_ranked", sa.Boolean(), nullable=False),
        sa.Column("matchtypes", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("leaderboard_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("leaderboards")
    # ### end Alembic commands ###
