"""add tournament_owners table

Revision ID: 93e6858602db
Revises: d05dd2f02a2c
Create Date: 2026-05-22 10:50:41.859514

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93e6858602db"
down_revision: str | Sequence[str] | None = "d05dd2f02a2c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament_owners",
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournaments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tournament_id", "user_id"),
    )
    op.create_index("ix_tournament_owners_user_id", "tournament_owners", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tournament_owners_user_id", table_name="tournament_owners")
    op.drop_table("tournament_owners")
    # ### end Alembic commands ###
