"""Initial schema: players, ratings, matches, match_players

Revision ID: a7d2f049b534
Revises:
Create Date: 2026-05-18 18:23:40.429954

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7d2f049b534"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("map_name", sa.String(), nullable=False),
        sa.Column("matchtype_id", sa.Integer(), nullable=False),
        sa.Column("leaderboard_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("staging", "in_progress", "completed", name="match_state", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.create_index("ix_matches_started_at", "matches", ["started_at"], unique=False)
    op.create_index("ix_matches_state", "matches", ["state"], unique=False)
    op.create_table(
        "players",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("steam_id", sa.String(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("clan_name", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("profile_id"),
    )
    op.create_table(
        "match_players",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("civilization_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum("win", "loss", name="match_outcome", native_enum=False),
            nullable=True,
        ),
        sa.Column("old_rating", sa.Integer(), nullable=True),
        sa.Column("new_rating", sa.Integer(), nullable=True),
        sa.Column("xp_gained", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("match_id", "profile_id"),
    )
    op.create_index("ix_match_players_profile_id", "match_players", ["profile_id"], unique=False)
    op.create_table(
        "player_ratings",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("leaderboard_id", sa.Integer(), nullable=False),
        sa.Column("current_rating", sa.Integer(), nullable=False),
        sa.Column("max_rating", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("streak", sa.Integer(), nullable=False),
        sa.Column("drops", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("rank_total", sa.Integer(), nullable=True),
        sa.Column("region_rank", sa.Integer(), nullable=True),
        sa.Column("region_rank_total", sa.Integer(), nullable=True),
        sa.Column("last_match_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["players.profile_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "leaderboard_id"),
    )
    op.create_index(
        "ix_player_ratings_leaderboard_current_rating",
        "player_ratings",
        ["leaderboard_id", "current_rating"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_ratings_leaderboard_current_rating", table_name="player_ratings")
    op.drop_table("player_ratings")
    op.drop_index("ix_match_players_profile_id", table_name="match_players")
    op.drop_table("match_players")
    op.drop_table("players")
    op.drop_index("ix_matches_state", table_name="matches")
    op.drop_index("ix_matches_started_at", table_name="matches")
    op.drop_table("matches")
    # ### end Alembic commands ###
