"""Add live_match_players table

Revision ID: b9e6b1a2dffb
Revises: a7d2f049b534
Create Date: 2026-05-21 15:27:45.538425

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9e6b1a2dffb"
down_revision: str | Sequence[str] | None = "a7d2f049b534"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "live_match_players",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("match_id", "profile_id"),
    )
    op.create_index(
        "ix_live_match_players_profile_id",
        "live_match_players",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_live_match_players_profile_id", table_name="live_match_players")
    op.drop_table("live_match_players")
    # ### end Alembic commands ###
