"""add is_captain to team_members

Revision ID: bd2d6eef00e8
Revises: 64de51a43607
Create Date: 2026-05-31 19:07:18.080252

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd2d6eef00e8"
down_revision: str | Sequence[str] | None = "64de51a43607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_members",
        sa.Column("is_captain", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.create_index(
        "uq_team_members_captain",
        "team_members",
        ["team_id"],
        unique=True,
        postgresql_where=sa.text("is_captain"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_team_members_captain", table_name="team_members", postgresql_where=sa.text("is_captain")
    )
    op.drop_column("team_members", "is_captain")
    # ### end Alembic commands ###
