"""Add teams and team_members tables

Revision ID: d05dd2f02a2c
Revises: cb3b9d0db5d8
Create Date: 2026-05-22 09:29:54.859478

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d05dd2f02a2c"
down_revision: str | Sequence[str] | None = "cb3b9d0db5d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("initials", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournaments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_teams_tournament_id", "teams", ["tournament_id"], unique=False)
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_id", "profile_id"),
    )
    op.create_index("ix_team_members_profile_id", "team_members", ["profile_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_team_members_profile_id", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_teams_tournament_id", table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
